# Generated by Django 5.2.10 on 2026-04-17 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('notification_type', models.CharField(choices=[('message', 'Message'), ('friend_request', 'Friend Request'), ('friend_accept', 'Friend Accept'), ('post_new', 'Post New'), ('post_like', 'Post Like'), ('post_comment', 'Post Comment'), ('group', 'Group'), ('system', 'System')], default='system', max_length=30)),
                ('target_username', models.CharField(blank=True, max_length=150)),
                ('conversation_id', models.PositiveIntegerField(blank=True, null=True)),
                ('post_id', models.PositiveIntegerField(blank=True, null=True)),
                ('group_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
