# Generated by Django 5.2.10 on 2026-04-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_conversation_is_active_conversation_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationparticipant',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
